This is makeindex, version 2.15 [TeX Live 2020] (kpathsea + Thai support).
Scanning style file ./Total.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file Total.acn....done (2 entries accepted, 0 rejected).
Sorting entries....done (2 comparisons).
Generating output file Total.acr....done (6 lines written, 0 warnings).
Output written in Total.acr.
Transcript written in Total.alg.
